name: Build
on:
  push:
    branches:
      - master
jobs:
  Build:
    name: Build and Publish
    # Run on all label events (won't be duplicated) or all push events or on PR syncs not from the same repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - id: vars
        run: echo "short_commit_hash=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

      - uses: gradle/wrapper-validation-action@v3

      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_cafestubeRepositoryUsername: ${{ secrets.REPO_USERNAME }}
          ORG_GRADLE_PROJECT_cafestubeRepositoryPassword: ${{ secrets.REPO_PASSWORD }}
          MINESTOM_VERSION: ${{ steps.vars.outputs.short_commit_hash }}
          MINESTOM_CHANNEL: release